---
title: "Bootstrapping with slipper"
output: html_notebook
---

```{r}
#Making test df1 (present)

A <-  round(runif(100,1,6)) 

B <-  round(runif(20,1,6)) 

C <-  round(runif(100,1,6)) 

D <-  round(runif(40,1,2)) 

E <-  round(runif(55,1,6))  

F <-  round(runif(100,1,4)) 

list1 <- list(A, B, C, D, E, F)
rm(A, B, C, D, E, F)

#Making vector of suspect positions for list1
pos1 <- c(1, 2, 3, 2, 5, 2)

#Making test df2 (absent)

A <-  round(runif(60,1,6)) #Present 

B <-  round(runif(100,1,6)) #Absent 

C <-  round(runif(89,1,4)) #Present 

D <-  round(runif(22,1,3)) #Absent

E <-  round(runif(100,1,6)) #Present 

F <-  round(runif(100,1,2)) #Absent

list2 <- list(A, B, C, D, E, F)
rm(A, B, C, D, E, F)

#Making vector of suspect positions for list2
pos2 <- c(1, 2, 3, 4, 5, 6)
```

```{r}
diag_param <- function(list1, list2, pos1, pos2){
    diagdf1 <- as.data.frame(matrix(ncol = 2, 
                                    nrow = length(list1)))
    
    for (i in 1:length(list1)){
        diagdf1[i,1]= sum(list1[[i]] == pos1[i])
        diagdf1[i,2] = sum(list1[[i]] != pos1[i])
        
        
    }
    
    diagdf2 <- as.data.frame(matrix(ncol = 2, 
                                        nrow = length(list2)))
    for (i in 1:length(list2)){
        diagdf2[i,1]= sum(list2[[i]] == pos2[i])
        diagdf2[i,2] = sum(list2[[i]] != pos2[i]) 
        
        diagdf <- cbind(diagdf1, diagdf2)
        names(diagdf) <- c("n11", "n21", "n12", "n22")
        diagdf = as.data.frame(sapply(diagdf, as.numeric))
    }
    return(diagdf)
}

```


#Bootstrap DI
```{r}

diag_param <- function(list1, list2, pos1, pos2){
    diagdf1 <- as.data.frame(matrix(ncol = 2, 
                                    nrow = length(list1)))
    
    for (i in 1:length(list1)){
        diagdf1[i,1]= sum(list1[[i]] == pos1[i])
        diagdf1[i,2] = sum(list1[[i]] != pos1[i])
        
        
    }
    
    diagdf2 <- as.data.frame(matrix(ncol = 2, 
                                        nrow = length(list2)))
    for (i in 1:length(list2)){
        diagdf2[i,1]= sum(list2[[i]] == pos2[i])
        diagdf2[i,2] = sum(list2[[i]] != pos2[i]) 
        
        diagdf <- cbind(diagdf1, diagdf2)
        names(diagdf) <- c("n11", "n21", "n12", "n22")
        
    }
    return(diagdf)
}

linedf <- diag_param(list1, list2, pos1, pos2)

ln_diag_ratio <- function(df){
    d<- (df$n11+0.5/((df$n11+df$n21)+0.5))/
        (df$n12+0.5/((df$n12+df$n22)+0.5))
    lnd <- log(d)
    ratio <- as.data.frame(cbind(d, lnd))
    
    return(ratio)
}


```

```{r}
#Can't do this properly until we learn how to use boot fx with multiple parameters
boot_lnd <- function(list1, list2, pos1, pos2){
  linedf <-  diag_param(list1, list2, pos1, pos2)
  ln_diag_ratio(linedf)
}
```


#Bootstrap p-value (chi)

#OTHER

```{r}
allfoil_cihigh <- function(linetabprops, sumlineup){
z <- 1:length(linetabprops)
for (i in 1:length(linetabprops)){
   z[i] <-  boot0975(linetabprops[i],sumlineup)
}
z
}

allfoil_cilow <- function(linetabprops, sumlineup){
    z <- 1:length(linetabprops)
    for (i in 1:length(linetabprops)){
        z[i] <-  boot025(linetabprops[i],sumlineup)
    }
    z
}
```


```{r}

gen_boot_propci <- function (lineuprops, perc=.05){
    if(perc >= 0 & perc <= 1) {
        quantile(lineuprops, probs = perc)
    }
    else {
        cat("Illegal value entered (must be proportion)")
    }
}

effsize_m_cifoils <- function(lineuprops){
  cilow <-  quantile(lineuprops, probs = .025)
  cihigh <- quantile(lineuprops, probs = .975)
    
}

effsize_m_cifoils(lineup_data_raw$lineup_1_data)
```

```{r}
lineup_prop_pos <- function (lineup_table,susp_pos){
    # lineup_table = table(lineup_vec)
    lineup_table[susp_pos]/sum(lineup_table)   
}

lineup_prop_pos(lineup_tables$lineup_1_table, 3)

lineup_tables$lineup_1_table[3]/sum(lineup_tables$lineup_1_table)
```
```{r}

```

