---
title: "Worksheet 2"
output: html_notebook
---

```{r}
#Making test df

A <-  round(runif(100,1,6)) #Present 

B <-  round(runif(100,1,6)) #Absent 

C <-  round(runif(100,1,6)) #Present 

D <-  round(runif(100,1,6)) #Absent

E <-  round(runif(100,1,6)) #Present 

F <-  round(runif(100,1,6)) #Absent

df1 <- cbind(A, B, C, D, E, F)
df1 <- as.data.frame(df1)
rm(A, B, C, D, E, F)

pos1 <- c(1, 2, 3, 4, 5, 6)


```

```{r}
A <-  round(runif(100,1,6)) #Present 

B <-  round(runif(100,1,6)) #Absent 

C <-  round(runif(100,1,6)) #Present 

D <-  round(runif(100,1,6)) #Absent

E <-  round(runif(100,1,6)) #Present 

F <-  round(runif(100,1,6)) #Absent

df2 <- cbind(A, B, C, D, E, F)
df2 <- as.data.frame(df2)
rm(A, B, C, D, E, F)

pos2 <- c(1, 2, 3, 4, 5, 6)
```

```{r}
diag_param <- function(df1, df2, pos1, pos2){
    diagdf1 <- as.data.frame(matrix(ncol = 2, 
                                    nrow = length(df1)))
    
    for (i in 1:ncol(df1)){
        diagdf1[i, 1]= sum(df1[i] == pos1[i])
        diagdf1[i,2] = sum(df1[i] != pos1[i])
        
        diagdf2 <- as.data.frame(matrix(ncol = 2, 
                                        nrow = length(df2)))
    }
    
    for (i in 1:ncol(df2)){
        diagdf2[i,1]= sum(df2[i] == pos2[i])
        diagdf2[i,2] = sum(df2[i] != pos2[i]) 
        
        diagdf <- cbind(diagdf1, diagdf2)
        names(diagdf) <- c("n11", "n21", "n12", "n22")
        
    }
    return(diagdf)
}
  
    
z <- diag_param(df1, df2, pos1, pos2)

```

```{r}
#Computing ln(d) for k lineups
#Needs df of diagnosticity parameters --> get using helper fx
ln_diag_ratio <- function(df){
    d<- (df$n11+0.5/((df$n11+df$n21)+0.5))/
                         (df$n12+0.5/((df$n12+df$n22)+0.5))
    lnd <- log(d)
    lnd <- as.data.frame(lnd)

    return(lnd)
}


```


```{r}
#Function to compute variance of ln(d) for k lineups
var_lnd <- function(df){
    var <- (df$n21/(df$n11+(df$n11+df$n21)))+(df$n22/(df$n12+(df$n12+df$n22)))
    var <- as.data.frame(var)
    return(var)
}


b <- var_lnd(z)
```

```{r}
#Function to compute weights for n diagnosticity ratios from k lineups

d_weights <- function(df){
    numerator <- df$n11*df$n12*(df$n11+df$n21)*(df$n12+df$n22)
    denominator <- df$n11*df$n22*(df$n11+df$n21)+
                   df$n12*df$n21*(df$n12+df$n22)
    wi <- numerator/denominator
    wi <- as.data.frame(wi)
    return(wi)
    
}



```

